'use strict';
const fs=require('fs'),os=require('os'),path=require('path');
const {run,load}=require('./config');
const {lint,query}=require('./catalog');
const MARKER='<!-- Generated by ACE database documentation; do not edit. -->\n\n';
function walk(dir) {
  return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{
    const p=path.join(dir,e.name);
    if(e.isSymbolicLink()) throw new Error('Generator emitted a symlink');
    return e.isDirectory()?walk(p):[p];
  });
}
function generate(config) {
  lint(config);
  const objects=query(config,'reference.sql');
  if(!objects.length) throw new Error('Catalog reference is empty; verify ownership scope and visibility');
  const work=fs.mkdtempSync(path.join(os.tmpdir(),'ace-reference-'));
  const generated=path.join(work,'reference');
  try {
    const cfg=path.join(work,'tbls.json');
    fs.writeFileSync(cfg,JSON.stringify({include:config.owned.map(s=>s+'.*'),exclude:config.excluded.map(s=>s+'.*'),er:{skip:true},format:{adjust:true}}));
    run('tbls',['doc','--config',cfg,'--sort','--without-er'],{env:{...config.pgEnv,TBLS_DSN:config.connection,TBLS_DOC_PATH:generated}});
    // tbls schema.json may contain connection metadata. It is not a published artifact.
    fs.rmSync(path.join(generated,'schema.json'),{force:true});
    if(!fs.existsSync(path.join(generated,'README.md'))) throw new Error('tbls produced no reference README');
    for(const file of walk(generated)) {
      if(!file.endsWith('.md')) throw new Error('Unexpected tbls artifact format');
      let content=fs.readFileSync(file,'utf8');
      if(content.includes(config.connection) || /(?:postgres(?:ql)?|pg):\/\//i.test(content)) throw new Error('Connection metadata detected in generated reference');
      content=content.replace(/\r\n/g,'\n');
      fs.writeFileSync(file,MARKER+content);
    }
    for(const o of objects.filter(o=>['table','partitioned table','view','materialized view','foreign table'].includes(o.kind))) {
      if(!fs.existsSync(path.join(generated,`${o.schema}.${o.name}.md`))) throw new Error('tbls omitted a scoped relation; coverage is incomplete');
    }
    const serialized=JSON.stringify(objects,null,2);
    if(serialized.includes(config.connection) || /(?:postgres(?:ql)?|pg):\/\//i.test(serialized)) throw new Error('Connection metadata detected in catalog comments');
    fs.writeFileSync(path.join(generated,'catalog.md'),MARKER+'# Catalog reference\n\nSource: migration-managed database catalog comments.\nRegenerate with the PostgreSQL pack generate-reference.sh command.\n\n```json\n'+serialized+'\n```\n');
    fs.writeFileSync(path.join(generated,'manifest.json'),JSON.stringify({generated:true,generator:'ACE PostgreSQL documentation',source:'migration-managed catalog comments',coverage:objects.map(o=>({identity:o.identity,file:'catalog.md'})),files:walk(generated).map(p=>path.relative(generated,p)).sort()},null,2)+'\n');
    // Rename on the target filesystem, retaining prior reference on failure.
    const parent=path.dirname(config.output);fs.mkdirSync(parent,{recursive:true});
    const stage=fs.mkdtempSync(path.join(parent,'.ace-reference-'));
    const next=path.join(stage,'next'),previous=path.join(stage,'previous');
    try {
      fs.cpSync(generated,next,{recursive:true});
      const existed=fs.existsSync(config.output);
      if(existed) fs.renameSync(config.output,previous);
      try {fs.renameSync(next,config.output);} catch(e) {if(existed) fs.renameSync(previous,config.output);throw e;}
    } finally {fs.rmSync(stage,{recursive:true,force:true});}
  } finally {fs.rmSync(work,{recursive:true,force:true});}
}
module.exports={generate,walk};
if(require.main===module) {
 try {if(process.argv.length>3) throw new Error('Usage: generate-reference.sh [config.json]');generate(load(process.argv[2]));console.log('Generated schema reference; review and commit it.');}
 catch(e){console.error(e.message);process.exit(1);}
}
