'use strict';
const fs=require('fs'),os=require('os'),path=require('path');
const {run,load}=require('../../postgres/scripts/config');
const {assertClean}=require('../../postgres/scripts/drift');
const HEADER='// Generated by Supabase CLI through ACE; do not edit.\n';
function generateTypes(config) {
  if(config.config.target.kind !== 'local') throw new Error('Type generation is local-only; replay preview migrations on the local stack');
  let status;
  try {status=JSON.parse(run('supabase',['status','--output','json'],{cwd:config.root}));}
  catch(e) {throw new Error('Local Supabase status failed: '+e.message);}
  let endpoint;
  try {endpoint=new URL(status.DB_URL);} catch {throw new Error('Local Supabase status did not supply a database endpoint');}
  if(endpoint.hostname.replace(/^\[|\]$/g,'')!==config.pgEnv.PGHOST || (endpoint.port||'5432')!==config.pgEnv.PGPORT || decodeURIComponent(endpoint.pathname.slice(1))!==config.pgEnv.PGDATABASE) throw new Error('Configured database differs from the local Supabase stack');
  const output=run('supabase',['gen','types','--local','--lang','typescript','--schema',config.owned.join(',')],{cwd:config.root});
  if(!output.includes('export type') || !output.includes('Database')) throw new Error('Supabase returned incomplete type output');
  return HEADER+output.replace(/\r\n/g,'\n');
}
function checkTypes(config) {
  assertClean(config,config.typesOutput);
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'ace-types-'));
  try {
    const file=path.join(temp,'database.types.ts');fs.writeFileSync(file,generateTypes(config));
    try {run('diff',['-u',config.typesOutput,file]);} catch(e) {throw new Error('Type drift check failed: '+e.message);}
  } finally {fs.rmSync(temp,{recursive:true,force:true});}
}
function writeTypes(config) {
  const output=generateTypes(config);fs.mkdirSync(path.dirname(config.typesOutput),{recursive:true});
  const temp=fs.mkdtempSync(path.join(path.dirname(config.typesOutput),'.ace-types-'));
  try {const file=path.join(temp,'next');fs.writeFileSync(file,output);fs.renameSync(file,config.typesOutput);}
  finally {fs.rmSync(temp,{recursive:true,force:true});}
}
module.exports={generateTypes,checkTypes,writeTypes};
if(require.main===module) {
 try {
  const [mode,file,...extra]=process.argv.slice(2);
  if(extra.length || (file && file.startsWith('-')) || !['check','generate'].includes(mode)) throw new Error('Usage: check-types.sh or generate-types.sh [config.json]');
  const config=load(file,{supabase:true});
  (mode==='check'?checkTypes:writeTypes)(config);console.log('Local generated types '+(mode==='check'?'match.':'written; review and commit.'));
 } catch(e) {console.error(e.message);process.exit(1);}
}
